Disable documentation publishing in CI
Comment out documentation publishing steps in CI workflow.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,3 @@
-
 name: CI
 
 on: [push, pull_request, workflow_dispatch]
@@ -46,45 +45,45 @@ jobs:
         run: |
            python -m unittest discover -v
 
-      # Publish built docs to gh-pages branch.
-      - name: Checkout documentation branch
-        if: matrix.python-version == '3.11'
-        uses: actions/checkout@v5
-        with:
-          ref: gh-pages
-          path: gh-pages
-          persist-credentials: false
+      # # Publish built docs to gh-pages branch.
+      # - name: Checkout documentation branch
+      #   if: matrix.python-version == '3.11'
+      #   uses: actions/checkout@v5
+      #   with:
+      #     ref: gh-pages
+      #     path: gh-pages
+      #     persist-credentials: false
 
-      - name: Build docs
-        if: matrix.python-version == '3.11'
-        run: |
-          pip install sphinx nbsphinx scikit-learn ipython numpydoc
-          sudo apt-get install pandoc texlive texlive-latex-extra dvipng
-          make docs
+      # - name: Build docs
+      #   if: matrix.python-version == '3.11'
+      #   run: |
+      #     pip install sphinx nbsphinx scikit-learn ipython numpydoc
+      #     sudo apt-get install pandoc texlive texlive-latex-extra dvipng
+      #     make docs
 
-      - uses: actions/upload-artifact@v4
-        if: (matrix.python-version == '3.11') && (github.event_name == 'pull_request')
-        with:
-          name: "doc_${{ github.event.pull_request.number }}"
-          path: docs/build/html
+      # - uses: actions/upload-artifact@v4
+      #   if: (matrix.python-version == '3.11') && (github.event_name == 'pull_request')
+      #   with:
+      #     name: "doc_${{ github.event.pull_request.number }}"
+      #     path: docs/build/html
 
-      - name: Move docs over
-        if: (matrix.python-version == '3.11') && (github.event_name == 'push')
-        run: |
-          ls
-          cp -r docs/build/html/* gh-pages/
-          cd gh-pages
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "New documentation" -a || true
-          # The above command will fail if no changes were present, so we ignore
-          # that.
+      # - name: Move docs over
+      #   if: (matrix.python-version == '3.11') && (github.event_name == 'push')
+      #   run: |
+      #     ls
+      #     cp -r docs/build/html/* gh-pages/
+      #     cd gh-pages
+      #     git config --local user.email "action@github.com"
+      #     git config --local user.name "GitHub Action"
+      #     git add .
+      #     git commit -m "New documentation" -a || true
+      #     # The above command will fail if no changes were present, so we ignore
+      #     # that.
 
-      - name: Push changes
-        if: (matrix.python-version == '3.11') && (github.event_name== 'push')
-        uses: ad-m/github-push-action@master
-        with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Push changes
+      #   if: (matrix.python-version == '3.11') && (github.event_name== 'push')
+      #   uses: ad-m/github-push-action@master
+      #   with:
+      #     branch: gh-pages
+      #     directory: gh-pages
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
